// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Vehicle struct {
	ID                 int32     `json:"id"`
	Brand              string    `json:"brand"`
	Model              string    `json:"model"`
	DateOfPurchase     time.Time `json:"date_of_purchase"`
	KmsRun             int32     `json:"kms_run"`
	OwnerName          string    `json:"owner_name"`
	OwnerContactNumber int32     `json:"owner_contact_number"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	QuotedPrice        int32     `json:"quoted_price"`
}
